"""Tests for SIPP reproductive-burden robustness surface."""

from pathlib import Path

import numpy as np
import pandas as pd

from gender_gap.models.sipp_robustness import build_sipp_robustness_table


def test_build_sipp_robustness_table_returns_partial_surface(tmp_path: Path):
    standardized = pd.DataFrame(
        [
            {
                "person_id": "H1_101",
                "calendar_year": 2023,
                "month": 1,
                "female": 1,
                "employed": 1,
                "labor_force_status": "employed",
                "usual_hours_week": 38,
                "actual_hours_last_week": 38,
                "paid_hourly": 1,
                "hourly_wage_real": 24.0,
                "weekly_earnings_real": 912.0,
                "overtime_indicator": 0,
                "multiple_jobholder": 0,
                "occupation_code": "1110",
                "industry_code": "5410",
                "state_fips": 6,
                "person_weight": 2.0,
            },
            {
                "person_id": "H1_102",
                "calendar_year": 2023,
                "month": 1,
                "female": 0,
                "employed": 1,
                "labor_force_status": "employed",
                "usual_hours_week": 40,
                "actual_hours_last_week": 40,
                "paid_hourly": 1,
                "hourly_wage_real": 32.0,
                "weekly_earnings_real": 1280.0,
                "overtime_indicator": 0,
                "multiple_jobholder": 0,
                "occupation_code": "1110",
                "industry_code": "5410",
                "state_fips": 6,
                "person_weight": 1.0,
            },
            {
                "person_id": "H2_101",
                "calendar_year": 2023,
                "month": 1,
                "female": 1,
                "employed": 1,
                "labor_force_status": "employed",
                "usual_hours_week": 35,
                "actual_hours_last_week": 35,
                "paid_hourly": 1,
                "hourly_wage_real": 28.0,
                "weekly_earnings_real": 980.0,
                "overtime_indicator": 0,
                "multiple_jobholder": 0,
                "occupation_code": "2210",
                "industry_code": "3110",
                "state_fips": 36,
                "person_weight": 1.5,
            },
            {
                "person_id": "H3_101",
                "calendar_year": 2023,
                "month": 1,
                "female": 0,
                "employed": 1,
                "labor_force_status": "employed",
                "usual_hours_week": 40,
                "actual_hours_last_week": 40,
                "paid_hourly": 1,
                "hourly_wage_real": 30.0,
                "weekly_earnings_real": 1200.0,
                "overtime_indicator": 0,
                "multiple_jobholder": 0,
                "occupation_code": "2210",
                "industry_code": "3110",
                "state_fips": 36,
                "person_weight": 1.0,
            },
        ]
    )
    raw = pd.DataFrame(
        [
            {
                "SSUID": "H1",
                "PNUM": 101,
                "MONTHCODE": 1,
                "TAGE": 30,
                "ESEX": 2,
                "EPNSPOUSE": 102,
                "EPNSPOUS_EHC": 102,
                "RPAR1SEX_EHC": 2,
                "RPAR2SEX_EHC": 1,
                "TAGE_FB": 27,
                "THHLDSTATUS": 2,
                "RPNCHILD1": 103,
                "RPNCHILD2": np.nan,
                "RPNCHILD3": np.nan,
                "RPNCHILD4": np.nan,
                "RPNCHILD5": np.nan,
                "RPNCHILD6": np.nan,
                "RPNCHILD7": np.nan,
                "RPNCHILD8": np.nan,
                "RPNCHILD9": np.nan,
                "RPNCHILD10": np.nan,
                "RPNCHILD11": np.nan,
            },
            {
                "SSUID": "H1",
                "PNUM": 102,
                "MONTHCODE": 1,
                "TAGE": 31,
                "ESEX": 1,
                "EPNSPOUSE": 101,
                "EPNSPOUS_EHC": 101,
                "RPAR1SEX_EHC": 2,
                "RPAR2SEX_EHC": 1,
                "TAGE_FB": np.nan,
                "THHLDSTATUS": 2,
                "RPNCHILD1": 103,
                "RPNCHILD2": np.nan,
                "RPNCHILD3": np.nan,
                "RPNCHILD4": np.nan,
                "RPNCHILD5": np.nan,
                "RPNCHILD6": np.nan,
                "RPNCHILD7": np.nan,
                "RPNCHILD8": np.nan,
                "RPNCHILD9": np.nan,
                "RPNCHILD10": np.nan,
                "RPNCHILD11": np.nan,
            },
            {
                "SSUID": "H1",
                "PNUM": 103,
                "MONTHCODE": 1,
                "TAGE": 4,
                "ESEX": 1,
                "EPNSPOUSE": np.nan,
                "EPNSPOUS_EHC": np.nan,
                "RPAR1SEX_EHC": 2,
                "RPAR2SEX_EHC": 1,
                "TAGE_FB": np.nan,
                "THHLDSTATUS": 2,
                "RPNCHILD1": np.nan,
                "RPNCHILD2": np.nan,
                "RPNCHILD3": np.nan,
                "RPNCHILD4": np.nan,
                "RPNCHILD5": np.nan,
                "RPNCHILD6": np.nan,
                "RPNCHILD7": np.nan,
                "RPNCHILD8": np.nan,
                "RPNCHILD9": np.nan,
                "RPNCHILD10": np.nan,
                "RPNCHILD11": np.nan,
            },
            {
                "SSUID": "H2",
                "PNUM": 101,
                "MONTHCODE": 1,
                "TAGE": 29,
                "ESEX": 2,
                "EPNSPOUSE": np.nan,
                "EPNSPOUS_EHC": np.nan,
                "RPAR1SEX_EHC": np.nan,
                "RPAR2SEX_EHC": np.nan,
                "TAGE_FB": np.nan,
                "THHLDSTATUS": 1,
                "RPNCHILD1": np.nan,
                "RPNCHILD2": np.nan,
                "RPNCHILD3": np.nan,
                "RPNCHILD4": np.nan,
                "RPNCHILD5": np.nan,
                "RPNCHILD6": np.nan,
                "RPNCHILD7": np.nan,
                "RPNCHILD8": np.nan,
                "RPNCHILD9": np.nan,
                "RPNCHILD10": np.nan,
                "RPNCHILD11": np.nan,
            },
            {
                "SSUID": "H3",
                "PNUM": 101,
                "MONTHCODE": 1,
                "TAGE": 33,
                "ESEX": 1,
                "EPNSPOUSE": np.nan,
                "EPNSPOUS_EHC": np.nan,
                "RPAR1SEX_EHC": np.nan,
                "RPAR2SEX_EHC": np.nan,
                "TAGE_FB": np.nan,
                "THHLDSTATUS": 1,
                "RPNCHILD1": np.nan,
                "RPNCHILD2": np.nan,
                "RPNCHILD3": np.nan,
                "RPNCHILD4": np.nan,
                "RPNCHILD5": np.nan,
                "RPNCHILD6": np.nan,
                "RPNCHILD7": np.nan,
                "RPNCHILD8": np.nan,
                "RPNCHILD9": np.nan,
                "RPNCHILD10": np.nan,
                "RPNCHILD11": np.nan,
            },
        ]
    )

    standardized_path = tmp_path / "sipp_standardized.parquet"
    raw_path = tmp_path / "pu2024.dta"
    standardized.to_parquet(standardized_path, index=False)
    raw.to_stata(raw_path, write_index=False)

    result = build_sipp_robustness_table(standardized_path, raw_path, survey_year=2023)

    assert not result.empty
    assert set(result["status"]) == {"ok_partial"}
    assert "status" in set(result["section"])
    assert "sample_size" in set(result["metric"])
